#!/usr/bin/env python3
"""
Visualization script for 2D vector data from the C++ textbook project.

This script reads vector data from CSV files generated by the C++ binary
and creates static visualizations (no animation - optimized for headless/remote systems).
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend for remote systems
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle as RectPatch
import argparse
import os


class VectorVisualizer:
    """Handles visualization of 2D vector data as static images."""
    
    @staticmethod
    def find_data_file(filename):
        """
        Find a data file in the current directory, parent, or src directory.
        
        Args:
            filename: Name of the CSV file to find
        
        Returns:
            Full path to the file if found
        
        Raises:
            FileNotFoundError: If file is not found
        """
        # Check current directory
        if os.path.exists(filename):
            return filename
        
        # Check parent directory (if running from scripts/)
        parent_path = os.path.join('..', filename)
        if os.path.exists(parent_path):
            return parent_path
        
        # Check src directory (if running from scripts/)
        src_path = os.path.join('..', 'src', filename)
        if os.path.exists(src_path):
            return src_path
        
        # Check src directory from current location
        src_local = os.path.join('src', filename)
        if os.path.exists(src_local):
            return src_local
        
        # Check grandparent directory (if running from elsewhere)
        grandparent_path = os.path.join('..', '..', filename)
        if os.path.exists(grandparent_path):
            return grandparent_path
        
        raise FileNotFoundError(f"Data file not found: {filename}")
    
    @staticmethod
    def load_vector_data(filename):
        """
        Load vector data from a CSV file.
        
        Args:
            filename: Path to CSV file with columns: x, y, type
        
        Returns:
            DataFrame with vector data
        """
        filepath = VectorVisualizer.find_data_file(filename)
        df = pd.read_csv(filepath)
        return df
    
    @staticmethod
    def load_rectangle_data(filename):
        """
        Load rectangle bounds from CSV file if it exists.
        
        Args:
            filename: Path to rectangle CSV file
        
        Returns:
            DataFrame with rectangle data or None if not found
        """
        try:
            filepath = VectorVisualizer.find_data_file(filename)
            df = pd.read_csv(filepath)
            return df
        except FileNotFoundError:
            return None
    
    @staticmethod
    def visualize_single_file(filename, output_file=None, dpi=100):
        """
        Create a static scatter plot from a data file and save it.
        
        Args:
            filename: Path to CSV file
            output_file: Output filename (default: vector_data.png)
            dpi: Resolution in dots per inch
        """
        if output_file is None:
            base = os.path.splitext(os.path.basename(filename))[0]
            output_file = f"{base}.png"
        
        # Load data
        vectors = VectorVisualizer.load_vector_data(filename)
        dist_type = vectors['type'].iloc[0] if len(vectors) > 0 else 'unknown'
        
        print(f"Loaded {len(vectors)} vectors of type '{dist_type}'")
        
        # Try to load rectangle data
        rect_data = VectorVisualizer.load_rectangle_data('rectangle_bounds.csv')
        
        # Create figure
        fig, ax = plt.subplots(figsize=(12, 10))
        
        # Get data
        x_data = vectors['x'].values
        y_data = vectors['y'].values
        
        # Auto-set limits with padding
        x_min, x_max = x_data.min(), x_data.max()
        y_min, y_max = y_data.min(), y_data.max()
        x_pad = (x_max - x_min) * 0.1 if x_max > x_min else 0.5
        y_pad = (y_max - y_min) * 0.1 if y_max > y_min else 0.5
        
        # Create scatter plot
        ax.scatter(x_data, y_data, alpha=0.6, s=10, c='blue', edgecolors='none')
        
        # Draw rectangle if available
        if rect_data is not None and len(rect_data) > 0:
            x_l = rect_data['x_left'].iloc[0]
            y_l = rect_data['y_bottom'].iloc[0]
            x_r = rect_data['x_right'].iloc[0]
            y_r = rect_data['y_top'].iloc[0]
            
            width = x_r - x_l
            height = y_r - y_l
            
            rect = RectPatch((x_l, y_l), width, height, 
                           linewidth=3, edgecolor='red', facecolor='none',
                           label='Rectangle Boundary')
            ax.add_patch(rect)
            ax.legend(loc='upper right')
            print(f"Drew rectangle: ({x_l}, {y_l}) to ({x_r}, {y_r})")
        
        ax.set_xlim(x_min - x_pad, x_max + x_pad)
        ax.set_ylim(y_min - y_pad, y_max + y_pad)
        ax.set_aspect('equal')
        ax.grid(True, alpha=0.3)
        ax.set_xlabel('X', fontsize=12)
        ax.set_ylabel('Y', fontsize=12)
        ax.set_title(f'Vector Distribution: {dist_type.capitalize()} ({len(vectors)} points)', 
                    fontsize=14, fontweight='bold')
        
        # Save figure
        plt.tight_layout()
        plt.savefig(output_file, dpi=dpi, bbox_inches='tight')
        print(f"Saved visualization to {output_file}")
        plt.close()
    
    @staticmethod
    def visualize_multiple_files(filenames, output_file=None, dpi=100):
        """
        Create a multi-subplot visualization from multiple data files.
        
        Args:
            filenames: List of CSV file paths
            output_file: Output filename (default: vector_distributions.png)
            dpi: Resolution in dots per inch
        """
        if output_file is None:
            output_file = "vector_distributions.png"
        
        # Create subplots
        n_files = len(filenames)
        n_cols = min(2, n_files)
        n_rows = (n_files + n_cols - 1) // n_cols
        
        fig, axes = plt.subplots(n_rows, n_cols, figsize=(14, 5*n_rows))
        if n_files == 1:
            axes = [axes]
        else:
            axes = axes.flatten() if n_rows > 1 else (axes.tolist() if n_cols > 1 else [axes])
        
        fig.suptitle('Vector Distributions', fontsize=16, fontweight='bold')
        
        # Try to load rectangle data
        rect_data = VectorVisualizer.load_rectangle_data('rectangle_bounds.csv')
        
        # Load and plot each file
        for i, filename in enumerate(filenames):
            if i >= len(axes):
                break
            
            ax = axes[i]
            vectors = VectorVisualizer.load_vector_data(filename)
            dist_type = vectors['type'].iloc[0] if len(vectors) > 0 else 'unknown'
            
            print(f"Loaded {len(vectors)} vectors from {filename}")
            
            # Get data
            x_data = vectors['x'].values
            y_data = vectors['y'].values
            
            # Auto-set limits with padding
            x_min, x_max = x_data.min(), x_data.max()
            y_min, y_max = y_data.min(), y_data.max()
            x_pad = (x_max - x_min) * 0.1 if x_max > x_min else 0.5
            y_pad = (y_max - y_min) * 0.1 if y_max > y_min else 0.5
            
            # Plot
            ax.scatter(x_data, y_data, alpha=0.6, s=8, c='blue', edgecolors='none')
            
            # Draw rectangle if available
            if rect_data is not None and len(rect_data) > 0:
                x_l = rect_data['x_left'].iloc[0]
                y_l = rect_data['y_bottom'].iloc[0]
                x_r = rect_data['x_right'].iloc[0]
                y_r = rect_data['y_top'].iloc[0]
                
                width = x_r - x_l
                height = y_r - y_l
                
                rect = RectPatch((x_l, y_l), width, height, 
                               linewidth=2, edgecolor='red', facecolor='none')
                ax.add_patch(rect)
            
            ax.set_xlim(x_min - x_pad, x_max + x_pad)
            ax.set_ylim(y_min - y_pad, y_max + y_pad)
            ax.set_aspect('equal')
            ax.grid(True, alpha=0.3)
            ax.set_xlabel('X')
            ax.set_ylabel('Y')
            ax.set_title(f'{os.path.basename(filename)}\n({len(vectors)} points)')
        
        # Hide unused subplots
        for i in range(len(filenames), len(axes)):
            axes[i].set_visible(False)
        
        # Save figure
        plt.tight_layout()
        plt.savefig(output_file, dpi=dpi, bbox_inches='tight')
        print(f"Saved visualization to {output_file}")
        plt.close()


def main():
    parser = argparse.ArgumentParser(
        description='Visualize 2D vector data from CSV files generated by the C++ project'
    )
    parser.add_argument('files', nargs='*', default=['vector_data.csv'],
                       help='CSV file(s) to visualize (default: vector_data.csv)')
    parser.add_argument('--output', '-o', type=str,
                       help='Output image filename (default: vector_data.png or vector_distributions.png)')
    parser.add_argument('--dpi', type=int, default=100,
                       help='Image resolution in DPI (default: 100)')
    
    args = parser.parse_args()
    
    # Check if files exist
    valid_files = []
    for f in args.files:
        try:
            filepath = VectorVisualizer.find_data_file(f)
            valid_files.append(f)
            print(f"Found: {f} -> {filepath}")
        except FileNotFoundError:
            print(f"Warning: File not found: {f}")
    
    if not valid_files:
        print("Error: No valid data files found")
        print("Please run the C++ binary first to generate vector_data.csv")
        return
    
    # Visualize
    if len(valid_files) == 1:
        VectorVisualizer.visualize_single_file(valid_files[0], args.output, args.dpi)
    else:
        VectorVisualizer.visualize_multiple_files(valid_files, args.output, args.dpi)


if __name__ == '__main__':
    main()
